export interface StrategyItem {
  id: string;
  icon: string;
  order: number;
  published: boolean;
  title: string;
  subtitle: string;
  description: string;
}

export const strategiesFr: StrategyItem[] = [
  {
    id: 'justice',
    icon: 'Scale',
    order: 1,
    published: true,
    title: 'Feuille de route Data & IA - Ministère de la Justice',
    subtitle: 'Budget 19M€ • 4 lignes d\'affaires',
    description: 'Définition et exécution de la feuille de route stratégique en données et IA. Mise en place de la gouvernance ministérielle avec comités stratégiques et cadre de gouvernance.',
  },
  {
    id: 'airbus',
    icon: 'Factory',
    order: 2,
    published: true,
    title: 'Stratégie Scale-Up A220 - Airbus',
    subtitle: 'Portefeuille 15M$ • Top 50 projets',
    description: 'Analyse et priorisation des 50 projets TI prioritaires (Ingénierie, Opérations, Programme, Service client). Développement du framework d\'architecture IA pour l\'Amérique du Nord.',
  },
  {
    id: 'separation',
    icon: 'Building2',
    order: 3,
    published: true,
    title: 'Stratégie TI de séparation Bombardier/Airbus',
    subtitle: 'Accord niveau CEOs • 15 FTE',
    description: 'Architecture stratégique de séparation des systèmes d\'information suite à l\'acquisition. Accord au niveau des CEOs et encadrement de l\'exécution avec une équipe de 15 personnes.',
  },
  {
    id: 'interior',
    icon: 'Shield',
    order: 4,
    published: true,
    title: 'Stratégie Data & IA - Ministère de l\'Intérieur',
    subtitle: 'Gouvernance multi-entités • Lab Data & IA',
    description: 'Mise en place de la gouvernance ministérielle en données et IA couvrant Police aux frontières, Sécurité routière, Immigration, Élections. Création du Lab Data & IA avec encadrement de 10 projets innovants. Métamodèle et catalogue des données.',
  },
  {
    id: 'riotinto',
    icon: 'TrendingUp',
    order: 5,
    published: true,
    title: 'Feuille de route Digital Twin - Rio Tinto',
    subtitle: 'Industrie minière • Jumeau numérique',
    description: 'Définition de la stratégie et architecture pour le jumeau numérique industriel. Roadmap IA pour l\'optimisation des opérations minières et données industrielles.',
  },
  {
    id: 'maritime',
    icon: 'Ship',
    order: 6,
    published: true,
    title: 'Hub Data Maritime - SODES',
    subtitle: 'Architecture centralisée',
    description: 'Conception de l\'architecture du hub de données maritimes centralisé. Stratégie d\'intégration multi-sources et mise en place de la gouvernance sectorielle.',
  },
  {
    id: 'nethris',
    icon: 'Briefcase',
    order: 7,
    published: true,
    title: 'Stratégie IA - Nethris/Desjardins',
    subtitle: 'Solution de paie • Agents IA',
    description: 'Feuille de route IA pour logiciel RH de gestion de paie. Architecture d\'agents IA conversationnels et RAG pour automatisation des processus métier.',
  },
  {
    id: 'curateur',
    icon: 'AlertTriangle',
    order: 8,
    published: true,
    title: 'Stratégie IA Fraude - Curateur Public',
    subtitle: 'Détection de fraude • MVP',
    description: 'Feuille de route stratégique IA pour cas d\'usage de détection de fraude. Architecture MVP et coaching IA pour l\'équipe interne.',
  },
  {
    id: 'expri',
    icon: 'Zap',
    order: 9,
    published: true,
    title: 'Démarche Expri - Transformation Agile SAFe',
    subtitle: 'SAFe • DevOps • OpenShift',
    description: 'Déploiement de SAFe sur plusieurs directions métier (Justice pénale, civile, pénitentiaire). Mise en place des métriques de bénéfices métier et vélocité. Adaptation des stratégies de test et déploiement DevOps avec migration cloud interne Alpha (OpenShift).',
  },
];

export const strategiesEn: StrategyItem[] = [
  {
    id: 'justice',
    icon: 'Scale',
    order: 1,
    published: true,
    title: 'Data & AI Roadmap - Ministry of Justice',
    subtitle: 'Budget €19M • 4 business lines',
    description: 'Definition and execution of the strategic roadmap for data and AI. Implementation of ministerial governance with strategic committees and governance framework.',
  },
  {
    id: 'airbus',
    icon: 'Factory',
    order: 2,
    published: true,
    title: 'A220 Scale-Up Strategy - Airbus',
    subtitle: 'Portfolio $15M • Top 50 projects',
    description: 'Analysis and prioritization of top 50 IT projects (Engineering, Operations, Program, Customer Service). Development of AI architecture framework for North America.',
  },
  {
    id: 'separation',
    icon: 'Building2',
    order: 3,
    published: true,
    title: 'IT Separation Strategy Bombardier/Airbus',
    subtitle: 'CEO-level agreement • 15 FTE',
    description: 'Strategic architecture for IT systems separation following acquisition. CEO-level agreement and execution management with a team of 15 people.',
  },
  {
    id: 'interior',
    icon: 'Shield',
    order: 4,
    published: true,
    title: 'Data & AI Strategy - Ministry of Interior',
    subtitle: 'Multi-entity governance • Data & AI Lab',
    description: 'Implementation of ministerial governance for data and AI covering Border Police, Road Safety, Immigration, Elections. Creation of Data & AI Lab with management of 10 innovative projects. Data metamodel and catalog.',
  },
  {
    id: 'riotinto',
    icon: 'TrendingUp',
    order: 5,
    published: true,
    title: 'Digital Twin Roadmap - Rio Tinto',
    subtitle: 'Mining industry • Digital twin',
    description: 'Strategy and architecture definition for industrial digital twin. AI roadmap for mining operations optimization and industrial data.',
  },
  {
    id: 'maritime',
    icon: 'Ship',
    order: 6,
    published: true,
    title: 'Maritime Data Hub - SODES',
    subtitle: 'Centralized architecture',
    description: 'Design of centralized maritime data hub architecture. Multi-source integration strategy and sectoral governance implementation.',
  },
  {
    id: 'nethris',
    icon: 'Briefcase',
    order: 7,
    published: true,
    title: 'AI Strategy - Nethris/Desjardins',
    subtitle: 'Payroll solution • AI agents',
    description: 'AI roadmap for HR payroll management software. Architecture of conversational AI agents and RAG for business process automation.',
  },
  {
    id: 'curateur',
    icon: 'AlertTriangle',
    order: 8,
    published: true,
    title: 'AI Fraud Strategy - Public Curator',
    subtitle: 'Fraud detection • MVP',
    description: 'Strategic AI roadmap for fraud detection use case. MVP architecture and AI coaching for internal team.',
  },
  {
    id: 'expri',
    icon: 'Zap',
    order: 9,
    published: true,
    title: 'Expri Initiative - SAFe Agile Transformation',
    subtitle: 'SAFe • DevOps • OpenShift',
    description: 'SAFe deployment across multiple business units (Criminal Justice, Civil Justice, Penitentiary). Implementation of business benefits and velocity metrics. Test strategy and DevOps deployment adaptation with Alpha internal cloud migration (OpenShift).',
  },
];
